Neos:
  Neos:
    fusion:
      autoInclude:
        'Webandco.Taxonomy': TRUE
    nodeTypes:
      groups:
        taxonomy:
          position: 'start'
          label: 'Taxonomy'

  Fusion:
    defaultContext:
      'Webandco.Taxonomy': 'Webandco\Taxonomy\Fusion\Helper\TaxonomyHelper'
